<Project>
  <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <MauiVersion>10.0.20</MauiVersion>
    <NofVersion>7.1.0-nightly.1163073.4d806de</NofVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- ASP.NET Core / Blazor -->
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
    <!-- MAUI -->
    <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <!-- Extensions -->
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
    <!-- ZJU Authentication -->
    <PackageVersion Include="login-ZJU.NET" Version="1.0.0-dev-26032001" />
    <PackageVersion Include="NOF.Application" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Contract" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Domain" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Hosting.AspNetCore" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Hosting.Maui" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Infrastructure.EntityFrameworkCore" Version="$(NofVersion)" />
    <PackageVersion Include="NOF.Infrastructure.EntityFrameworkCore.SQLite" Version="$(NofVersion)" />
  </ItemGroup>
</Project>