<Project>
  <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <MauiVersion>10.0.0</MauiVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- ASP.NET Core / Blazor -->
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
    
    <!-- MAUI -->
    <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    
    <!-- Extensions -->
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
    
    <!-- Playwright -->
    <PackageVersion Include="Microsoft.Playwright" Version="1.51.0" />
  </ItemGroup>
</Project>
