using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ReQuantum;

[Generator]
public class ViewLocatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var viewModelDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetViewModelInfo(ctx))
            .Where(static m => m is not null);

        var compilationAndModels = context.CompilationProvider.Combine(viewModelDeclarations.Collect());
        context.RegisterSourceOutput(compilationAndModels, static (spc, source) => Execute(spc, source.Right));
    }

    private static ViewModelInfo? GetViewModelInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        if (semanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol || classSymbol.IsAbstract)
        {
            return null;
        }

        var baseType = classSymbol.BaseType;
        while (baseType is not null)
        {
            if (baseType.ConstructedFrom.Name == "ViewModelBase")
            {
                if (baseType.TypeArguments.Length == 1)
                {
                    var viewSymbol = baseType.TypeArguments[0];
                    return new ViewModelInfo
                    {
                        ViewModelFullName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        ViewFullName = viewSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    };
                }
            }
            baseType = baseType.BaseType;
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<ViewModelInfo?> viewModels)
    {
        if (viewModels.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace ReQuantum.Generated;");
        sb.AppendLine();
        sb.AppendLine("public sealed class GeneratedViewLocator : global::Avalonia.Controls.Templates.IDataTemplate");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::System.IServiceProvider _serviceProvider;");
        sb.AppendLine();
        sb.AppendLine("    public GeneratedViewLocator(global::System.IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _serviceProvider = serviceProvider;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public bool Match(object? data) => data is global::ReQuantum.Infrastructure.Abstractions.IViewModel;");
        sb.AppendLine();
        sb.AppendLine("    public global::Avalonia.Controls.Control? Build(object? param)");
        sb.AppendLine("    {");
        sb.AppendLine("        var viewType = param switch");
        sb.AppendLine("        {");

        foreach (var vm in viewModels.Where(v => v is not null))
        {
            sb.AppendLine($"            {vm!.ViewModelFullName} _ => typeof({vm.ViewFullName}),");
        }
        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        if (viewType is null)");
        sb.AppendLine("        {");
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var view = global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities");
        sb.AppendLine("            .GetServiceOrCreateInstance(_serviceProvider, viewType) as global::Avalonia.Controls.Control;");
        sb.AppendLine();
        sb.AppendLine("        view?.DataContext = param;");
        sb.AppendLine();
        sb.AppendLine("        return view;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedViewLocator.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private class ViewModelInfo
    {
        public string ViewModelFullName { get; set; } = string.Empty;
        public string ViewFullName { get; set; } = string.Empty;
    }
}
