<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\**" />
    <EmbeddedResource Remove="Repositories\**" />
    <None Remove="Repositories\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="login-ZJU.NET" />
    <PackageReference Include="NOF.Application" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReQuantum.Domain\ReQuantum.Domain.csproj" />
    <ProjectReference Include="..\ReQuantum.Contract\ReQuantum.Contract.csproj" />
    <ProjectReference Include="..\ReQuantum.Shared\ReQuantum.Shared.csproj" />
  </ItemGroup>

</Project>
