<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NOF.Contract" />
    <PackageReference Include="NOF.Domain" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReQuantum.Application.Abstraction\ReQuantum.Application.Abstraction.csproj" />
  </ItemGroup>

</Project>
