//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReQuantum.Assets.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReQuantum.Assets.I18n.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The account may be locked. 的本地化字符串。
        /// </summary>
        public static string AccountMayBeLocked {
            get {
                return ResourceManager.GetString("AccountMayBeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Event 的本地化字符串。
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Note 的本地化字符串。
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Todo 的本地化字符串。
        /// </summary>
        public static string AddTodo {
            get {
                return ResourceManager.GetString("AddTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already logged in 的本地化字符串。
        /// </summary>
        public static string AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calendar 的本地化字符串。
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CollapseMenu 的本地化字符串。
        /// </summary>
        public static string CollapseMenu {
            get {
                return ResourceManager.GetString("CollapseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Due Date 的本地化字符串。
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Due: {0:yyyy-MM-dd HH:mm} 的本地化字符串。
        /// </summary>
        public static string DueOn {
            get {
                return ResourceManager.GetString("DueOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Due Time 的本地化字符串。
        /// </summary>
        public static string DueTime {
            get {
                return ResourceManager.GetString("DueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Time 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter event content... 的本地化字符串。
        /// </summary>
        public static string EnterEventContent {
            get {
                return ResourceManager.GetString("EnterEventContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter event title... 的本地化字符串。
        /// </summary>
        public static string EnterEventTitle {
            get {
                return ResourceManager.GetString("EnterEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter note... 的本地化字符串。
        /// </summary>
        public static string EnterNote {
            get {
                return ResourceManager.GetString("EnterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter note content... 的本地化字符串。
        /// </summary>
        public static string EnterNoteContent {
            get {
                return ResourceManager.GetString("EnterNoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter your password 的本地化字符串。
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter todo content... 的本地化字符串。
        /// </summary>
        public static string EnterTodoContent {
            get {
                return ResourceManager.GetString("EnterTodoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter your username 的本地化字符串。
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End time cannot be earlier than or equal to start time 的本地化字符串。
        /// </summary>
        public static string EventEndTimeBeforeStart {
            get {
                return ResourceManager.GetString("EventEndTimeBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are creating an event in the past 的本地化字符串。
        /// </summary>
        public static string EventInPast {
            get {
                return ResourceManager.GetString("EventInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Events 的本地化字符串。
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Events - {0:MMM dd, yyyy} 的本地化字符串。
        /// </summary>
        public static string EventsOnDate {
            get {
                return ResourceManager.GetString("EventsOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpandMenu 的本地化字符串。
        /// </summary>
        public static string ExpandMenu {
            get {
                return ResourceManager.GetString("ExpandMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get execution value. 的本地化字符串。
        /// </summary>
        public static string FailedToGetExecutionValue {
            get {
                return ResourceManager.GetString("FailedToGetExecutionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get exponent. 的本地化字符串。
        /// </summary>
        public static string FailedToGetExponent {
            get {
                return ResourceManager.GetString("FailedToGetExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get modulus. 的本地化字符串。
        /// </summary>
        public static string FailedToGetModulus {
            get {
                return ResourceManager.GetString("FailedToGetModulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fri 的本地化字符串。
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello, World 的本地化字符串。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect username or password. 的本地化字符串。
        /// </summary>
        public static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language Settings 的本地化字符串。
        /// </summary>
        public static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logged in as: 的本地化字符串。
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging in... 的本地化字符串。
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed: {0} 的本地化字符串。
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login successful. 的本地化字符串。
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout successful 的本地化字符串。
        /// </summary>
        public static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mon 的本地化字符串。
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} more items 的本地化字符串。
        /// </summary>
        public static string MoreItems {
            get {
                return ResourceManager.GetString("MoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No events 的本地化字符串。
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No notes 的本地化字符串。
        /// </summary>
        public static string NoNotes {
            get {
                return ResourceManager.GetString("NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note 的本地化字符串。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notes 的本地化字符串。
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User is not logged in. 的本地化字符串。
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No todos 的本地化字符串。
        /// </summary>
        public static string NoTodos {
            get {
                return ResourceManager.GetString("NoTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter password 的本地化字符串。
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter username 的本地化字符串。
        /// </summary>
        public static string PleaseEnterUsername {
            get {
                return ResourceManager.GetString("PleaseEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Repeat Times： 的本地化字符串。
        /// </summary>
        public static string RepeatTimes {
            get {
                return ResourceManager.GetString("RepeatTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔁 Repeat eveyweek 的本地化字符串。
        /// </summary>
        public static string RepeatWeekly {
            get {
                return ResourceManager.GetString("RepeatWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sat 的本地化字符串。
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Language 的本地化字符串。
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Time 的本地化字符串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sun 的本地化字符串。
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync ZJU 的本地化字符串。
        /// </summary>
        public static string SyncCoursesZju {
            get {
                return ResourceManager.GetString("SyncCoursesZju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thu 的本地化字符串。
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are creating a todo in the past 的本地化字符串。
        /// </summary>
        public static string TodoInPast {
            get {
                return ResourceManager.GetString("TodoInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Todos 的本地化字符串。
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tue 的本地化字符串。
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown error occurred. 的本地化字符串。
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wed 的本地化字符串。
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Week 的本地化字符串。
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}/{1} 的本地化字符串。
        /// </summary>
        public static string YearMonthFormat {
            get {
                return ResourceManager.GetString("YearMonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZJU SSO Account Management 的本地化字符串。
        /// </summary>
        public static string ZjuSsoAccountManagement {
            get {
                return ResourceManager.GetString("ZjuSsoAccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZJU SSO Login 的本地化字符串。
        /// </summary>
        public static string ZjuSsoLogin {
            get {
                return ResourceManager.GetString("ZjuSsoLogin", resourceCulture);
            }
        }
    }
}
